---
title: "Known knowns, unknown knowns and unknowns: Uncertainty in state assignment"
author: "The team"
date: "last updated: `r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: [default, "slides-theme.css"]
    lib_dir: libs
    nature:
      ratio: '16:9'
      highlightStyle: github
      highlightLines: true
      slideNumberFormat: ''
      titleSlideClass: [center, middle]
---

```{r setup, include=FALSE, echo=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(comment = "")

library(tidyverse)
theme_set(theme_light())
update_geom_defaults("point", list(size = 2)) 
library(here)
library(nimble)
```


## Plan

+ Some theory

+ Sex, **breeding** and **disease states** (house finches Faustino et al. 2004 et Conn & Cooch 2009)

+ Trap-dependence, **memory**

+ Individual heterogeneity w/ finite mixtures. Gray wolves case study with or without transition. Cite Daniel's EES paper. Sarah Cons Biol paper as well. With vs without heterogeneity, compare with wAIC. Cite Daniel's paper. 

+ Add matrices like in multistate slides for examples we will not cover

---
## Further reading

+ Pradel 2005 (memory model)
+ Gimenez et al. 2012

+ Turek, D., Wehrhahn, C. & Gimenez, O. Bayesian non-parametric detection heterogeneity in ecological models. Environ Ecol Stat (2021). https://doi.org/10.1007/s10651-021-00489-1

+ Conn, P.B. and Cooch, E.G. (2009), Multistate capture–recapture analysis under imperfect state observation: an application to disease models. Journal of Applied Ecology, 46: 486-492. https://doi.org/10.1111/j.1365-2664.2008.01597.x
