---
title: "Take-home messages"
author: "The team"
date: "last updated: `r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: [default, "slides-theme.css"]
    lib_dir: libs
    nature:
      ratio: '16:9'
      highlightStyle: github
      highlightLines: true
      slideNumberFormat: ''
      titleSlideClass: [center, middle]
---

```{r setup, include=FALSE, echo=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(comment = "")
```


## Make the best of your data with HMMs

+ Here is [a searchable list](applistHMM.html) of HMM analyses of capture-recapture data.

+ This list is not exhaustive, please get in touch with us if you'd like to add a reference.

---
## Bayesian capture-recapture analysis with HMMs

+ Make your ecological question explicit. 

+ Think of observations and states first. 

+ Then write down the observation and transition matrices on paper. 

+ Start simple, all parameters constant for example. Make sure convergence is reached.

+ Add complexity one step at a time. 

---
## Bayesian capture-recapture analysis with HMMs


+ Use simulations to better understand your model. 

+ Do not try to optimize your code. Make it work first, then think of optimization. 

> "Premature optimization is the root of all evil" -Donald Knuth (creator of TeX and author of "The Art of Computer Programming") (e.g. <https://stackify.com/premature-optimization-evil/>)

+ Read [Bayesian workflow](https://arxiv.org/abs/2011.01808) by Gelman et al. (2021).

<!-- --- -->
<!-- ## Nimble -->

<!-- + [TO BE COMPLETED BY ALL] -->

<!-- + Go for `nimbleMCMC()` if standard needs.  -->

<!-- + Unleash full `Nimble` potential for improving MCMC or implementing new distributions.  -->

---
## Till next time

+ The Slack space will remain for some time. Happy to answer questions you might have related to the workshop. 

+ Website will be updated with

    + video recordings
    + your feedbacks
    + a FAQ section based on your questions

+ A book is on its way. More in 2022 hopefully.
